PACKAGECONFIG:append:rk3066 = " lima"
PACKAGECONFIG:append:rk3188 = " lima"
PACKAGECONFIG:append:rk3288 = " libclc panfrost"
PACKAGECONFIG:append:rk3328 = " lima"
PACKAGECONFIG:append:rk3399 = " libclc panfrost"
PACKAGECONFIG:append:rk3566 = " libclc panfrost"
PACKAGECONFIG:append:rk3568 = " libclc panfrost"
PACKAGECONFIG:append:px30 = " libclc panfrost"
