PACKAGECONFIG:append:rk3288 = " panfrost"
PACKAGECONFIG:append:rk3328 = " lima"
PACKAGECONFIG:append:rk3399 = " panfrost"
PACKAGECONFIG:append:rk3566 = " panfrost"
PACKAGECONFIG:append:rk3568 = " panfrost"
PACKAGECONFIG:append:px30 = " panfrost"
